language: go

go:
  - "1.10.x"
  - tip

env:
  REPO_NAME: github.com/blk-io/crux

before_install:
  - sudo apt-get update -qq && sudo apt-get install -y -qq libdb-dev libpthread-stubs0-dev # This is hopefully temporary until we completely remove BerkeleyDB.
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $TRAVIS_BUILD_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get ./...
  - curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - unzip protoc-3.5.1-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - make setup

script:
  - make build
  - make test
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
